var sctLink = {
    "Alpha CT" : "https://www.alphassl.com",
    "CNNIC CT" : "https://ctserver.cnnic.cn",
    "Certly.IO" : "https://log.certly.io",
    "Cloudflare “Nimbus2017”" : "https://ct.cloudflare.com/logs/nimbus2017",
    "Cloudflare “Nimbus2018”" : "https://ct.cloudflare.com/logs/nimbus2018/",
    "Cloudflare “Nimbus2019”" : "https://ct.cloudflare.com/logs/nimbus2019/",
    "Cloudflare “Nimbus2020”" : "https://ct.cloudflare.com/logs/nimbus2020/",
    "Cloudflare “Nimbus2021”" : "https://ct.cloudflare.com/logs/nimbus2021/",
    "Cloudflare “Nimbus2022”" : "https://ct.cloudflare.com/logs/nimbus2022/",
    "Cloudflare “Nimbus2023”" : "https://ct.cloudflare.com/logs/nimbus2023/",
    "DigiCert Nessie2018" : "https://nessie2018.ct.digicert.com/log",
    "DigiCert Nessie2019" : "https://nessie2019.ct.digicert.com/log",
    "DigiCert Nessie2020" : "https://nessie2020.ct.digicert.com/log",
    "DigiCert Nessie2021" : "https://nessie2021.ct.digicert.com/log",
    "DigiCert Nessie2022" : "https://nessie2022.ct.digicert.com/log",
    "DigiCert Nessie2023" : "https://nessie2023.ct.digicert.com/log",
    "DigiCert Server" : "https://ct1.digicert-ct.com/log",
    "DigiCert Server 2" : "https://ct2.digicert-ct.com/log",
    "DigiCert Yeti2018" : "https://yeti2018.ct.digicert.com/log",
    "DigiCert Yeti2019" : "https://yeti2019.ct.digicert.com/log",
    "DigiCert Yeti2020" : "https://yeti2020.ct.digicert.com/log",
"DigiCert Yeti2021": "https://yeti2021.ct.digicert.com/log",
"DigiCert Yeti2022": "https://yeti2022.ct.digicert.com/log",
"DigiCert Yeti2023": "https://yeti2023.ct.digicert.com/log",
"GDCA 1": "https://log.gdca.com.cn",
"GDCA 2": "https://log2.gdca.com.cn",
"GDCA CT #1": "https://ct.gdca.com.cn",
"GDCA CT #2": "https://ct.gdca.com.cn",
"Google “Argon2017”": "https://ct.googleapis.com/logs/argon2017",
"Google “Argon2018”": "https://ct.googleapis.com/logs/argon2018",
"Google “Argon2019”": "https://ct.googleapis.com/logs/argon2019",
"Google “Argon2020”": "https://ct.googleapis.com/logs/argon2020",
"Google “Argon2021”": "https://ct.googleapis.com/logs/argon2021",
"Google “Argon2022”": "https://ct.googleapis.com/logs/argon2022",
"Google “Aviator”": "https://ct.googleapis.com/aviator",
"Google “Crucible”": "https://ct.googleapis.com/crucible",
"Google “Daedalus”": "https://ct.googleapis.com/daedalus",
"Google “Icarus”": "https://ct.googleapis.com/icarus",
"Google “Pilot”": "https://ct.googleapis.com/pilot",
"Google “Rocketeer”": "https://ct.googleapis.com/rocketeer",
"Google “Skydiver”": "https://ct.googleapis.com/skydiver",
"Google “Solera2018”": "https://ct.googleapis.com/solera2018",
"Google “Solera2019”": "https://ct.googleapis.com/solera2019",
"Google “Solera2020”": "https://ct.googleapis.com/solera2020",
"Google “Solera2021”": "https://ct.googleapis.com/solera2021",
"Google “Solera2022”": "https://ct.googleapis.com/solera2022",
"Google “Submariner”": "https://ct.googleapis.com/submariner",
"Google “Testtube”": "https://ct.googleapis.com/testtube",
"Google “Xenon2018”": "https://ct.googleapis.com/logs/xenon2018",
"Google “Xenon2019”": "https://ct.googleapis.com/logs/xenon2019",
"Google “Xenon2020”": "https://ct.googleapis.com/logs/xenon2020",
"Google “Xenon2021”": "https://ct.googleapis.com/logs/xenon2021",
"Google “Xenon2022”": "https://ct.googleapis.com/logs/xenon2022",
"Izenpe": "https://ct.izenpe.com",
"Izenpe “Argi”": "https://ct.izenpe.eus",
"Let“s Encrypt ”Clicky”": "https://clicky.ct.letsencrypt.org",
"Nordu “flimsy”": "https://flimsy.ct.nordu.net",
"Nordu “plausible”": "https://plausible.ct.nordu.net",
"PuChuangSiDa CT": "https://www.certificatetransparency.cn/ct",
"SHECA CT 1": "http://ctlog.sheca.com",
"SHECA CT 2": "https://ct.sheca.com",
"Sectigo (Comodo) “Dodo” CT": "https://dodo.ct.comodo.com",
"Sectigo (Comodo) “Mammoth” CT": "https://mammoth.ct.comodo.com",
"Sectigo (Comodo) “Sabre” CT": "https://sabre.ct.comodo.com",
"StartCom": "https://ct.startssl.com",
"Symantec": "https://ct.ws.symantec.com",
"Symantec Deneb": "https://deneb.ws.symantec.com",
"Symantec “Sirius”": " 	https://sirius.ws.symantec.com",
"Symantec “Vega”": "https://vega.ws.symantec.com",
"Up In The Air “Behind the Sofa”": "https://ct.filippo.io/behindthesofa",
"Venafi": "https://ctlog.api.venafi.com",
"Venafi Gen2 CT": " 	https://ctlog-gen2.api.venafi.com",
"WoSign": "https://ctlog.wosign.com",
"WoSign 2": "https://ctlog2.wosign.com",
"WoSign CT #1": "https://ct.wosign.com"
}

export default (sct) => {
    return `<a href="${new URL(sctLink[sct]).href}">${sctLink[sct]}</a>`;
  };