var sctLink = {
    "Cloudflare “Nimbus2017”" : "https://ct.cloudflare.com/logs/nimbus2017",
    "Cloudflare “Nimbus2018”" : "https://ct.cloudflare.com/logs/nimbus2018/",
    "Cloudflare “Nimbus2019”" : "https://ct.cloudflare.com/logs/nimbus2019/",
    "Cloudflare “Nimbus2020”" : "https://ct.cloudflare.com/logs/nimbus2020/",
    "Cloudflare “Nimbus2021”" : "https://ct.cloudflare.com/logs/nimbus2021/",
    "Cloudflare “Nimbus2022”" : "https://ct.cloudflare.com/logs/nimbus2022/",
    "Cloudflare “Nimbus2023”" : "https://ct.cloudflare.com/logs/nimbus2023/",
    "DigiCert Nessie2018" : "https://ct.cloudflare.com/logs/nessie2018",
    "DigiCert Nessie2019" : "https://ct.cloudflare.com/logs/nessie2019",
    "DigiCert Nessie2020" : "https://ct.cloudflare.com/logs/nessie2020",
    "DigiCert Nessie2021" : "https://ct.cloudflare.com/logs/nessie2021",
    "DigiCert Nessie2022" : "https://ct.cloudflare.com/logs/nessie2022",
    "DigiCert Nessie2023" : "https://ct.cloudflare.com/logs/nessie2023",
    "DigiCert Server" : "https://ct.cloudflare.com/logs/digicert",
    "DigiCert Server 2" : "https://ct.cloudflare.com/logs/digicert2",
    "DigiCert Yeti2018" : "https://ct.cloudflare.com/logs/yeti2018",
    "DigiCert Yeti2019" : "https://ct.cloudflare.com/logs/yeti2019",
    "DigiCert Yeti2020" : "https://ct.cloudflare.com/logs/yeti2020",
    "DigiCert Yeti2021": "https://ct.cloudflare.com/logs/yeti2021",
    "DigiCert Yeti2022": "https://ct.cloudflare.com/logs/yeti2022",
    "DigiCert Yeti2023": "https://ct.cloudflare.com/logs/yeti2023",
    "Google “Argon2017”": "https://ct.cloudflare.com/logs/argon2017",
    "Google “Argon2018”": "https://ct.cloudflare.com/logs/argon2018",
    "Google “Argon2019”": "https://ct.cloudflare.com/logs/argon2019",
    "Google “Argon2020”": "https://ct.cloudflare.com/logs/argon2020",
    "Google “Argon2021”": "https://ct.cloudflare.com/logs/argon2021",
    "Google “Argon2022”": "https://ct.cloudflare.com/logs/argon2022",
    "Google “Aviator”": "https://ct.cloudflare.com/logs/aviator",
    "Google “Icarus”": "https://ct.cloudflare.com/logs/icarus",
    "Google “Pilot”": "https://ct.cloudflare.com/logs/pilot",
    "Google “Rocketeer”": "https://ct.cloudflare.com/logs/rocketeer",
    "Google “Skydiver”": "https://ct.cloudflare.com/logs/skydiver",
    "Google “Xenon2018”": "https://ct.cloudflare.com/logs/xenon2018",
    "Google “Xenon2019”": "https://ct.cloudflare.com/logs/xenon2019",
    "Google “Xenon2020”": "https://ct.cloudflare.com/logs/xenon2020",
    "Google “Xenon2021”": "https://ct.cloudflare.com/logs/xenon2021",
    "Google “Xenon2022”": "https://ct.cloudflare.com/logs/xenon2022",
    "Sectigo (Comodo) “Mammoth” CT": "https://ct.cloudflare.com/logs/mammoth",
    "Sectigo (Comodo) “Sabre” CT": "https://ct.cloudflare.com/logs/sabre"
}

export default (sct) => {
    return `<a href="${new URL(sctLink[sct]).href}">Link : ${sctLink[sct]}</a>`;
  };